server:
  port: 8401
spring:
  application:
    name: cloud-sentinel-service
  cloud:
    discovery:
      server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如端口被占用会自动从8719开始依次+1，直到找到未被占用的端口
        port: 8791
